Match User portal-hub
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    X11Forwarding no
    AllowTcpForwarding no
    PermitTunnel no
    PermitTTY yes
    AllowAgentForwarding yes
